# 256 色端末を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

# ウィンドウとペインの番号を 1 から開始
set -g base-index 1
setw -g pane-base-index 1
# ウィンドウを閉じた時に番号を詰める
set-option -g renumber-windows on

# ステータスバーの位置を設定
set -g status-position top
# ステータスバーの長さを設定
set -g status-left-length 90
set -g status-right-length 90
# ステータスバーの内容を設定
set -g status-fg "colour255"
set -g status-bg "colour238"
set -g status-left '#H:[#P]'                # 左: マシン名・ペイン番号
set -g status-right '[%Y-%m-%d(%a) %H:%M]'  # 右: 日付
setw -g window-status-format " #I: #W "     # 中央: ウィンドウのインデックス・名前
setw -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I: #W"  # 現在のウィンドウの内容
# ウィンドウ番号などを中央に表示
set -g status-justify centre
# ステータスバーを1秒毎に描画し直す
set -g status-interval 1

# Prefix キーを Ctrl-b から Ctrl-j に変更
set -g prefix C-j
unbind C-b

# Prefix + vim のキーバインドでペインを移動する
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# Prefix + vim のキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# Ctrl-o でペインをローテーションしながら移動
bind -n C-o select-pane -t :.+

# Prefix + Ctrl-h/l でウィンドウ切り替え
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Prefix + | でペインを垂直分割する
bind \\ split-window -h -c "#{pane_current_path}"
# Prefix + - でペインを水平分割する
bind - split-window -v -c "#{pane_current_path}"

# ESCの反応速度
set -g escape-time 0

# マウス操作を有効にする
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# コピペ関連の設定
setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection

bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "win32yank.exe -i"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "win32yank.exe -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "win32yank.exe -i"

unbind-key -T prefix p
bind-key p run "win32yank.exe -o | tmux load-buffer - && tmux paste-buffer"
