# 256 色端末を使用する
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

# set -g status-style 'bg=colour234,fg=white'

# ウィンドウとペインの番号を 1 から開始
set -g base-index 1
setw -g pane-base-index 1
# ウィンドウを閉じた時に番号を詰める
set-option -g renumber-windows on

# ステータスバーの位置を設定
set -g status-position top
# Prefix キーを Ctrl-b から Ctrl-j に変更
set -g prefix C-j
unbind C-b

# Prefix + vim のキーバインドでペインを移動する
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
# Prefix + vim のキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# Ctrl-o でペインをローテーションしながら移動
bind -n C-o select-pane -t :.+

# Prefix + Ctrl-h/l でウィンドウ切り替え
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Prefix + | でペインを垂直分割する
bind \\ split-window -h -c "#{pane_current_path}"
# Prefix + - でペインを水平分割する
bind - split-window -v -c "#{pane_current_path}"

# ESCの反応速度
set -g escape-time 0

# マウス操作を有効にする
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# コピペ関連の設定
# OS が Linux の時は xsel を使う
if-shell -b '[ "$(uname)" = "Linux" ]' {
  if-shell -b 'grep -qi microsoft /proc/sys/kernel/osrelease' \
    "set -s copy-command 'clip.exe'" \
    "set -s copy-command 'xsel --clipboard --input'"
}
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
set -s set-clipboard off
bind -Tcopy-mode-vi v send -X begin-selection
bind -Tcopy-mode-vi y send -X copy-pipe-and-cancel
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel
